Oadmin/urls.py
from django.urls import path
from . import views 
from django.conf.urls.static import static
from django.conf import settings

app_name = 'Oadmin'
#URLConf
urlpatterns = [
    path('', views.admin_view_selectg.as_view(), name = 'home'),
    path('show/', views.show.as_view(), name = 'show'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

django_ini/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


#URLConf
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('Oadmin/', include('Oadmin.urls')), 
    path('', TemplateView.as_view(template_name='home/main.html')),
]

Oadmin/models.py
from django.db import models

# Create your models here.
class FilesUpload(models.Model):
    file = models.FileField()

home/models.py
from django.db import models

# Create your models here.

Oadmin/views.py
import yaml
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import FilesUpload

class admin_view_selectg(LoginRequiredMixin, View):
    template_name = 'Oadmin/selectg.html'

    def get(self, request):
        files = FilesUpload.objects.values_list('id','file')
        return render(request, self.template_name, {'files': files})

    def post(self, request):
        file2 = request.FILES["file"]
        document = FilesUpload.objects.create(file = file2)
        document.save()
        return HttpResponse("file uploaded")
 

class show_all(LoginRequiredMixin, View):
    template_name = 'Oadmin/show_all.html'

    def get(self, request):
        files_names = request.GET.get('file_content', '')  # Retrieve the file content from the query parameter
        return render(request, self.template_name, {'content': files_names})


class show(LoginRequiredMixin, View):
    template_name = 'Oadmin/show.html'

    def get(self, request):
        file_content = request.GET.get('file_content', '')  # Retrieve the file content from the query parameter
        return render(request, self.template_name, {'content': file_content})

home/views.py
from django.shortcuts import render

# Create your views here.

Oadmin/templates/Oadmin/selectg.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Ini to YAML</title>
  <style>
    textarea {
      width: 100%;
      height: 300px;
    }
  </style>
</head>
<body>
  {% load static %}
  <div id="demo">
    
    {% for id, name in files.items %}
     <p> Name of the file<a href = "">{{ id }} : {{ name }} </a> </p>
    {% endfor %}
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}

      <h2>YAML File</h2>
      <br>

      
      <input type="file" name="file" id="fileInput">
      <input type="submit" value="Upload">
    </form>
  </div>
</body>
</html>

Oadmin/templates/Oadmin/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>{{ file_content }}</p>
    </form>
    
</body>
</html>

home/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}My Website{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block extra_css %}{% endblock %}
</head>
<body>
    <header>
        <h1>My Website</h1>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'contact' %}">Contact</a></li>
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>

    <footer>
        <p>&copy; {% now "Y" %} My Website. All rights reserved.</p>
    </footer>

    <script src="{% static 'js/script.js' %}"></script>
    {% block extra_js %}{% endblock %}
</body>
</html>

home/templates/home/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>Welcome to the Home Page</h1>
    <p>Choose an option:</p>
    <ul>
        <li><a href="{% url 'Oadmin:home' %}">Oadmin</a></li>
    </ul>
    
</body>
</html>